### ISSUE TITLE
Failure: Project Validation on running initial setup

### ISSUE THREAD

**Issue by JasonPhat** [kentcdodds/react-suspense#2]
![image](https://github.com/kentcdodds/react-suspense/assets/15261156/f2105e71-2651-4c3d-ab54-4c769b272fb6)

I got this error after running trying to run the following setup commands: 

```
git clone https://github.com/kentcdodds/react-suspense.git
cd react-suspense
npm run setup --silent
```

- git version 2.44.0.windows.1
- node v16.18.1
- npm 8.19.2

**Comment by kentcdodds** [comment]
Hmm... Could you try upgrading to Node 18 or 20? I'm running Node 20 and it's working well. It could be some dependency broke recently.

**Comment by JasonPhat** [comment]
I use nvm to handle my node installs. I think my npm version went wrong somewhere. So I installed node version 20, then ran `npm install -g npm`, which seemed to fix it. Thanks
