### ISSUE TITLE
Exercises' titles are not displayed on the dashboard

### ISSUE THREAD

**Issue by vasilii-kovalev** [kentcdodds/react-suspense#25]
I've just setup and launched the project locally and...
![image](https://user-images.githubusercontent.com/10310491/97348869-cfcb3580-189f-11eb-8c8c-fd3722a08435.png)

The titles are displayed correctly on the exercise pages:
![image](https://user-images.githubusercontent.com/10310491/97349003-fbe6b680-189f-11eb-82ea-6516a000c963.png)

There is no the problem in [production version](https://react-suspense.netlify.app/) though.

P.S.: OS - Windows 10.

**Comment by vasilii-kovalev** [comment]
Oh, and some other titles are not displayed in the exercises:
![image](https://user-images.githubusercontent.com/10310491/97351750-3c93ff00-18a3-11eb-83a3-190f6d8edf3d.png)

In [production version](https://react-suspense.netlify.app/1):
![image](https://user-images.githubusercontent.com/10310491/97351813-533a5600-18a3-11eb-8edb-43f1b26a365a.png)

**Comment by kentcdodds** [comment]
Hi @vasilii-kovalev, could you make sure you're using the latest version of the repo?

**Comment by vasilii-kovalev** [comment]
And another thing: I can see something unusual in the tabs names as well:
![image](https://user-images.githubusercontent.com/10310491/97351934-795ff600-18a3-11eb-9a00-8a4b7434cd76.png)

1 - React Suspense (local)
2 - React Suspense (prod)
3 - React Performance (local)

**Comment by vasilii-kovalev** [comment]
> Hi @vasilii-kovalev, could you make sure you're using the latest version of the repo? I just tried it locally myself and it works fine.

I've just cloned it a couple of minutes ago. To be clear:
![image](https://user-images.githubusercontent.com/10310491/97352624-f25f4d80-18a3-11eb-880e-93ecb3346d83.png)

**Comment by kentcdodds** [comment]
Huh, odd. I'm not seeing this locally. I just deleted `package-lock.json` and updated it again and pushed that update. Give it another try?

**Comment by vasilii-kovalev** [comment]
Ok, I will try that.

**Comment by vasilii-kovalev** [comment]
Unfortunately, nothing has changed.

**Comment by vasilii-kovalev** [comment]
Ok, I've tried to:
* reset the code state to several older commits (that were made about a week ago), always deleting `node_modules` folder and running `setup` script again
* completely remove the folder and clone it again
* check how other workshops work (because I can see `update all deps` commits there as well) - for instance, [react-performance](https://github.com/kentcdodds/react-performance) works OK.

So the problem is with this repository only.

**Comment by vasilii-kovalev** [comment]
```js
// 🚨 PLEASE HEED ALL WARNINGS AROUND THIS WORKSHOP TELLING YOU THAT THIS
// IS UNSTABLE SOFTWARE...
// I just don't want to have to type "unstable_" prefixes everywhere
React.useTransition = React.unstable_useTransition
React.SuspenseList = React.unstable_SuspenseList
ReactDOM.createRoot = ReactDOM.unstable_createRoot

codegen`module.exports = require('@kentcdodds/react-workshop-app/codegen')({
  options: {concurrentMode: true}
})`
```

I've removed `{ options: {concurrentMode: true} }` part to make it the same as in React Performance workshop - nothing has changed.
Can it be related to the renaming?

**Comment by Aprillion** [comment]
FWIW: I just cloned the repo on Win 10, Node 14.13.1, and it works fine for me, not able to reproduce the issue...

**Comment by vasilii-kovalev** [comment]
Ok, I'll finish the workshop first and take a look at the issue closely later then.

**Comment by vasilii-kovalev** [comment]
I've spent time debugging [this file](https://github.com/kentcdodds/react-workshop-app/blob/master/src/load-files.js) and finally found out the problem.
![image](https://user-images.githubusercontent.com/10310491/97662684-c05b1080-1a88-11eb-8c6d-5ed3dc803dd7.png)

It seems that [splitting](https://github.com/kentcdodds/react-workshop-app/blob/master/src/load-files.js#L29) should be OS-sensitive.

@kentcdodds

**Comment by vasilii-kovalev** [comment]
I can see a rule in Prettier to apply `ls` EOL, but it doesn't work:
![image](https://user-images.githubusercontent.com/10310491/97663536-ebdefa80-1a8a-11eb-9345-03237c51985a.png)

**Comment by kentcdodds** [comment]
Thank you so much for doing this investigation! It's been fixed I think. Could you please check?

**Comment by vasilii-kovalev** [comment]
Yes, it works now, thank you!
