### ISSUE TITLE
Server responses with status 400 for "fetch approaches" examples

### ISSUE THREAD

**Issue by vasilii-kovalev** [kentcdodds/react-suspense#26]
![image](https://user-images.githubusercontent.com/10310491/97482103-c1941c80-1966-11eb-8568-52a4ea16e6ca.png)

All the three examples have the issue.

["fetch-on-render" example on production environment](https://react-suspense.netlify.app/isolated/examples/fetch-approaches/fetch-on-render.js).

**Comment by kentcdodds** [comment]
@all-contributors please add @vasilii-kovalev for bugs
