### ISSUE TITLE
fetchPokemon does not handle errors correctly

### ISSUE THREAD

**Issue by intrueder** [kentcdodds/react-suspense#41]
API response:
```json
{"data":{"errors":[{"message":"Unsupported pokemon: \"pikacha\". Try \"bulbasaur\""}]}}
```

but the function does not check `data` before getting the errors:
```js
      if (response.errors) {
        return Promise.reject(
          new Error(response.errors.map(e => e.message).join('\n')),
        )
      }
```

in addition it rejects a promise with a `string` message instead of `Error` object:
```js
return Promise.reject(`No pokemon with the name "${name}"`)
```
so `ErrorFallback` can't handle it and shows nothing

**Comment by kentcdodds** [comment]
Hmmm... I thought @cesarcf had addressed this in https://github.com/kentcdodds/react-suspense/pull/37 🤔

**Comment by intrueder** [comment]
I'm not sure it was a complete fix, because there are two places where the promise is being rejected, but only one was changed from `Error` to `String`.
Moreover, `ErrorFallback` component relies on `Error` object since it outputs `error.message` and not just `error`.

Anyway, this is a different issue, and my previous comment is more about checking the result from the API.
Currently the code checks `response.errors`, but should check `response.data.errors`:

```js
      if (response.data.errors) {
        return Promise.reject(
          new Error(response.data.errors.map(e => e.message).join('\n')),
        )
      }
```

**Comment by kentcdodds** [comment]
I think I misunderstood the issue @cesarcf was talking about in #37 and that change should be reverted. Doing that now.

**Comment by kentcdodds** [comment]
@all-contributors please add @intrueder for bugs

**Comment by intrueder** [comment]
I just realized, that `response.errors` is probably there to handle server errors, and if pokemon name is misspelled then error will be handled by `else` branch, that's why there is no check for `response.data.errors`
But... what is a server error then? I tried to simulate it by breaking a graphql request (some invalid variable: `variables: {namez: name.toLowerCase()}`) and the response has no `errors` field:

![image](https://user-images.githubusercontent.com/182339/101935316-8e8cac00-3be7-11eb-85a8-33dde773fb41.png)

At the same time GraphiQL console works in a very different way, I can't see `data.errors` field in the result:

![image](https://user-images.githubusercontent.com/182339/101934102-c7c41c80-3be5-11eb-87b4-08eadcb03b75.png)

**Comment by kentcdodds** [comment]
Keep in mind that we don't actually have a real server in this workshop (so it works offline): https://github.com/kentcdodds/react-suspense/blob/c6a440d3b04b5ba6693423b6c8e65f5fd9c8dbaa/src/backend.js#L32

**Comment by intrueder** [comment]
Haha 😄 Totally forgot about this. Thanks!
So, here is the problem:
https://github.com/kentcdodds/react-suspense/blob/c6a440d3b04b5ba6693423b6c8e65f5fd9c8dbaa/src/backend.js#L42

I believe it should be:
```js
        ctx.errors([
          {
            message: `Unsupported pokemon: "${req.variables.name}". Try "${randomName}"`,
          },
        ])
```

**Comment by kentcdodds** [comment]
Oh! Nice! I didn't realize that API exists. Would you be interested in [making a PR](https://makeapullrequest.com) for that?
