### ISSUE TITLE
Problem in exercise 2

### ISSUE THREAD

**Issue by guidelli** [kentcdodds/react-suspense#51]
When i enter 'aaa' as a pokemon name in the form,  the ui of the ErrorFallback component is shown during a fraction of second then the following error is displayed on the screen as a not catched exception: 

**Error: Unsupported pokemon: "aaaa". Try "mewtwo"
(anonymous function)
D:/prof/react2/react-suspense/src/pokemon.js:68
  65 | })
  66 | .then(response => {
  67 |   if (response.errors) {
> 68 |     return Promise.reject(
     | ^  69 |       new Error(response.errors.map(e => e.message).join('\n')),
  70 |     )
  71 |   }**

**Comment by FranciscoKloganB** [comment]
For those wondering how to "fix" this, see #43. It appears it is just an overlay which only appears in `dev`.
