### ISSUE TITLE
Issue on exercice 7

### ISSUE THREAD

**Issue by gkueny** [kentcdodds/react-suspense#52]
Hi kent,

I've just encountered a bug that I can't explain and fix.

## Reproduction

* Clone `react-suspense` repo
* Follow install instruction
* Run the app 
* Go to http://localhost:3000/isolated/final/07.js
* Click on a pokemon name

<details>
<summary>
GET http://localhost:3000/pokemoney/mew 500 (Internal Server Error)
</summary>
<pre>{"status":500,"message":"Cannot read property 'includes' of undefined"}</pre>
</details>

 & 

<details>
 <summary>
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
</summary>
<pre>
nav-bar.js:49 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at NavBar (nav-bar.js:49)
    at renderWithHooks (react-dom.development.js:15590)
    at updateFunctionComponent (react-dom.development.js:18021)
    at mountLazyComponent (react-dom.development.js:18381)
    at beginWork (react-dom.development.js:19961)
    at HTMLUnknownElement.callCallback (react-dom.development.js:310)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:359)
    at invokeGuardedCallback (react-dom.development.js:421)
    at beginWork$1 (react-dom.development.js:25127)
    at performUnitOfWork (react-dom.development.js:23859)
    at workLoopConcurrent (react-dom.development.js:23845)
    at renderRootConcurrent (react-dom.development.js:23802)
    at performConcurrentWorkOnRoot (react-dom.development.js:23035)
    at workLoop (scheduler.development.js:595)
    at flushWork (scheduler.development.js:550)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:162)
</pre>
</details>

<img width="1518" alt="Capture d’écran 2021-02-26 à 22 25 22" src="https://user-images.githubusercontent.com/10655690/109356839-93293e00-7881-11eb-843e-81aa881265c5.png">

I will continue to investigate & specify the issue if I find it

**Comment by gkueny** [comment]
Not sure if it's related but I have this Error in all the exercices 

<details>
<summary>index.js:1034 Uncaught RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].</summary>
<pre>
index.js:1034 Uncaught RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].
    at index.js:1034
    at ServiceWorkerContainer.<anonymous> (index.js:1200)
</pre>
</details>

**Comment by gkueny** [comment]
I tried to debug but I don't know the `msw` part well enough to understand where it goes.

I got lost in `public/mockServiceWorker.js` :

```
// l240
function sendToClient(client, message) {
  return new Promise((resolve, reject) => {
    const channel = new MessageChannel()

    channel.port1.onmessage = event => {
      if (event.data && event.data.error) {
        reject(event.data.error)
      } else {
        resolve(event.data)
      }
    }
```

I also tried to debug `src/backend.js` but it doesn't seem to reach this part of the code.

My guess is the error is somewhere in `msw` or `@kentcdodds/react-workshop-app` part but I didn't understand where the request with error 500 was going after `sendToClient` function

**Comment by gkueny** [comment]
Ok, I found the commit that cause the issue. This is 41105a07a0f0ab992050d7f2bb3d045666e38470

If I reset before this commit (go to f69de30f743213c17534d7edec16e7e1bc60ec40), exercice work as expected

**Comment by kentcdodds** [comment]
Thanks for all the research you've done here! I don't work Fridays, but I do work Saturdays so I'll look at this today 👍

**Comment by kentcdodds** [comment]
Figured it out in: https://github.com/kentcdodds/react-workshop-app/releases/tag/v3.0.2

Thanks for the report both of you!

@all-contributors please add @gkueny for bugs

**Comment by kentcdodds** [comment]
@all-contributors please add @nawok for bugs

**Comment by gkueny** [comment]
thanks @kentcdodds ! All works as expected 🎉
