### ISSUE TITLE
Unable to start the application

### ISSUE THREAD

**Issue by adebiyial** [kentcdodds/react-suspense#55]
The `npm run setup --silent` fails

<img width="1604" alt="epic-react-suspence-fail" src="https://user-images.githubusercontent.com/18689106/109400812-2da18400-794b-11eb-9012-7455f75c4ab0.png">

Other commands also fail:

1. `npm install --legacy-peer-deps`
2. `yarn start`

I run Node v15.8.0, git version 2.15.0, npm version 7.5.2.

**Comment by kentcdodds** [comment]
Looks like there was a dependency installation issue. Could you run `npm install` and tell me what the output is with that?

**Comment by adebiyial** [comment]
I think so. Here's a screenshot of the log
<img width="1360" alt="epic-react-suspense-fail" src="https://user-images.githubusercontent.com/18689106/109402934-364d8680-795a-11eb-9517-0e63b4a4a75a.png">

**Comment by kentcdodds** [comment]
This is quite odd. It appears that your system has a hard time installing dependencies which include binary files like `which`.

It's possible this is because of a change or bug in npm 7. Any chance you could downgrade to npm 6 and try again?

**Comment by adebiyial** [comment]
Downgrading to npm version 6.14.10 does the trick. I still run into XCode issues when I run `npm run setup --silent` and some other peer-dep issues with `npm install` but nothing enough to block progress.

Thank you for helping me.

**Comment by kentcdodds** [comment]
Glad that's working. I'll look at npm v7 support eventually.
