### ISSUE TITLE
Minor typo in toc sidebar

### ISSUE THREAD

**Issue by andrejilderda** [kentcdodds/react-suspense#57]
Hi Kent, just noticed this minor 'startTranistion' typo in the sidebar on this module:
https://epicreact.dev/modules/react-suspense/usetransition-solution

<img width="414" alt="Pasted_Image_14_03_2021__15_34" src="https://user-images.githubusercontent.com/487182/111072486-1a5def00-84db-11eb-885b-32bf09ebfa23.png">

**Comment by kentcdodds** [comment]
cc @dealingwith
