### ISSUE TITLE
Error Boundary not working properly

### ISSUE THREAD

**Issue by dynamite-bud** [kentcdodds/react-suspense#68]
React Error Boundary is not working properly.
Pokemon Error Boundary catches the error but then after a few seconds falls back to webpack error screen.

![image](https://user-images.githubusercontent.com/41326026/160987933-99f1de16-a28c-423a-ad7e-13d31fcf8b5e.png)

falls back to webpack errors

![image](https://user-images.githubusercontent.com/41326026/160988020-fa8d2522-eb52-4a2e-bddf-5046ed4366d2.png)

when I close the checkbox to the side

![image](https://user-images.githubusercontent.com/41326026/160988072-73daf02d-781f-4807-aa87-f4bd0792b141.png)

I don't see this behavior in the videos.

My Code for exercise **06.js** but I see this kind of behavior in every exercise.

`// Suspense with a custom hook`
`// http://localhost:3000/isolated/exercise/06.js`

`import * as React from 'react'`
`import {
  fetchPokemon,
  getImageUrlForPokemon,
  PokemonInfoFallback,
  PokemonForm,
  PokemonDataView,
  PokemonErrorBoundary,
} from '../pokemon'
import {createResource, preloadImage} from '../utils'`

`const PokemonInfo = React.lazy(() =>
  import('../lazy/pokemon-info-render-as-you-fetch'),
)`
`const SUSPENSE_CONFIG = {
  timeoutMs: 4000,
  busyDelayMs: 300,
  busyMinDurationMs: 700,
}`

`const pokemonResourceCache = {}`

`function getPokemonResource(name) {
  const lowerName = name.toLowerCase()
  let resource = pokemonResourceCache[lowerName]
  if (!resource) {
    resource = createPokemonResource(lowerName)
    pokemonResourceCache[lowerName] = resource
  }
  return resource
}`

`function createPokemonResource(pokemonName) {
  const data = createResource(fetchPokemon(pokemonName))
  const image = createResource(preloadImage(getImageUrlForPokemon(pokemonName)))
  return {data, image}
}`

`function usePokemonResource(pokemonName) {
  const [startTransition, isPending] = React.useTransition(SUSPENSE_CONFIG)
  const [pokemonResource, setPokemonResource] = React.useState(null)

  React.useEffect(() => {
    if (!pokemonName) {
      setPokemonResource(null)
      return
    }
    startTransition(() => {
      setPokemonResource(getPokemonResource(pokemonName))
    })
  }, [pokemonName, startTransition])
  return [pokemonResource, isPending]
}`

`function App() {
  const [pokemonName, setPokemonName] = React.useState('')
  const [pokemonResource, isPending] = usePokemonResource(pokemonName)

  function handleSubmit(newPokemonName) {
    setPokemonName(newPokemonName)
  }

  function handleReset() {
    setPokemonName('')
  }

  return (
    <div className="pokemon-info-app">
      <PokemonForm pokemonName={pokemonName} onSubmit={handleSubmit} />
      <hr />
      <div className={`pokemon-info ${isPending ? 'pokemon-loading' : ''}`}>
        {pokemonResource ? (
          <PokemonErrorBoundary
            onReset={handleReset}
            resetKeys={[pokemonResource]}
          >
            <React.Suspense
              fallback={<PokemonInfoFallback name={pokemonName} />}
            >
              <PokemonInfo pokemonResource={pokemonResource} />
            </React.Suspense>
          </PokemonErrorBoundary>
        ) : (
          'Submit a pokemon'
        )}
      </div>
    </div>
  )
}`

`export default App`

**Comment by forbesd7** [comment]
Just a +1 on this, having the same errors. I sent an email to team@epicreact.dev as well outlining this issue.

**Comment by kentcdodds** [comment]
This is a built-in functionality of create-react-app and there's nothing we can do about it I'm afraid. FWIW, it's *supposed* to be helpful, but it's kinda annoying when you're testing the error boundary functionality. It only happens during development.
