### ISSUE TITLE
Error using node version 16

### ISSUE THREAD

**Issue by sp-reach** [kentcdodds/react-suspense#71]
When using nvm and node version 16 the `node setup` command fails.
![image](https://user-images.githubusercontent.com/80424905/171485975-148a605d-6289-46d9-a986-d8c161c55d81.png)

The reason I ran into this issue, was because the previous module "testing" required node 16 to work.

EDIT: This is in relation to a windows dev env.

**Comment by Nargonath** [comment]
I'm on `v16.15.1` and I have no problem installing

**Comment by sp-reach** [comment]
@Nargonath  did you install it on a windows, linux, or macos env? Sorry I didn't make the initial comment clear this is for windows envs.

**Comment by kentcdodds** [comment]
Could you try again? There have been a couple changes since you opened this issue.

**Comment by Nargonath** [comment]
@sp-reach I'm on Windows 11 but I use WSL2 (Windows Sub-Linux 2). If you're on Windows I highly recommend using it, it's usually a pain to develop directly on Windows to be honest.

**Comment by sp-reach** [comment]
![image](https://user-images.githubusercontent.com/80424905/190108792-3d2def6c-9608-4b9c-8321-c7ebbecde665.png)
This seems now to be resolved thanks!



> @sp-reach I'm on Windows 11 but I use WSL2 (Windows Sub-Linux 2). If you're on Windows I highly recommend using it, it's usually a pain to develop directly on Windows to be honest.

@Nargonath  I am using wsl2 and it is the "better way" in my opinion, however I was debugging for a friend the windows env.

**Comment by Nargonath** [comment]
Alright, glad it got fixed for you @sp-reach.
