### ISSUE TITLE
Reset not working - Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by ACPK** [kentcdodds/react-suspense#77]
Code: https://github.com/kentcdodds/react-suspense/blob/main/src/final/02.js

I receive an "Uncaught ReferenceError: process is not defined" error when searching for a Pokemon that doesn't exist (ex: "errortest"). Consequently, the "try again" button is not clickable.

**Comment by Boamorte8** [comment]
I have the same problem, the app is stucked after enter a wrong pokemon name

**Comment by kentcdodds** [comment]
Thanks for letting me know. This should be fixed in the latest version of the workshop.
